// Government Module — Mock Data Service
// All demo/placeholder data lives here so it can be replaced with a real
// GovernmentService that calls a backend API without touching any UI widget.

import 'govt_models.dart';

class GovtMockData {
  GovtMockData._();

  // ─── Vaccination Campaigns ────────────────────────────────────────────────

  static List<VaccinationCampaign> getCampaigns() => [
        VaccinationCampaign(
          campaignId: 'CAMP001',
          name: 'FMD Immunisation Drive — Erode',
          disease: 'Foot-and-Mouth Disease (FMD)',
          targetDistrict: 'Erode',
          targetBlock: 'All Blocks',
          targetVillages: '87 villages',
          animalSpecies: 'Cattle, Buffalo',
          startDate: DateTime.now().subtract(const Duration(days: 10)),
          endDate: DateTime.now().add(const Duration(days: 20)),
          targetAnimals: 50000,
          vaccinatedAnimals: 38250,
          assignedTeams: ['VT-01', 'VT-02', 'VT-03', 'VT-05'],
          status: CampaignStatus.active,
          createdAt: DateTime.now().subtract(const Duration(days: 15)),
        ),
        VaccinationCampaign(
          campaignId: 'CAMP002',
          name: 'HS Vaccination — Namakkal',
          disease: 'Haemorrhagic Septicaemia (HS)',
          targetDistrict: 'Namakkal',
          targetBlock: 'Namakkal, Tiruchengode',
          targetVillages: '42 villages',
          animalSpecies: 'Cattle',
          startDate: DateTime.now().subtract(const Duration(days: 3)),
          endDate: DateTime.now().add(const Duration(days: 27)),
          targetAnimals: 22000,
          vaccinatedAnimals: 8100,
          assignedTeams: ['VT-04', 'VT-06'],
          status: CampaignStatus.active,
          createdAt: DateTime.now().subtract(const Duration(days: 5)),
        ),
        VaccinationCampaign(
          campaignId: 'CAMP003',
          name: 'PPR Goat Vaccination — Salem',
          disease: 'Peste des Petits Ruminants (PPR)',
          targetDistrict: 'Salem',
          targetBlock: 'Omalur',
          targetVillages: '28 villages',
          animalSpecies: 'Goat, Sheep',
          startDate: DateTime.now().add(const Duration(days: 5)),
          endDate: DateTime.now().add(const Duration(days: 35)),
          targetAnimals: 15000,
          vaccinatedAnimals: 0,
          assignedTeams: ['VT-07'],
          status: CampaignStatus.planned,
          createdAt: DateTime.now().subtract(const Duration(days: 1)),
        ),
        VaccinationCampaign(
          campaignId: 'CAMP004',
          name: 'Brucellosis Control — Coimbatore',
          disease: 'Brucellosis',
          targetDistrict: 'Coimbatore',
          targetBlock: 'Mettupalayam, Annur',
          targetVillages: '55 villages',
          animalSpecies: 'Cattle, Buffalo',
          startDate: DateTime.now().subtract(const Duration(days: 45)),
          endDate: DateTime.now().subtract(const Duration(days: 5)),
          targetAnimals: 18500,
          vaccinatedAnimals: 18200,
          assignedTeams: ['VT-08', 'VT-09'],
          status: CampaignStatus.completed,
          createdAt: DateTime.now().subtract(const Duration(days: 50)),
        ),
      ];

  // ─── Lab Samples ──────────────────────────────────────────────────────────

  static List<LabSample> getLabSamples() => [
        LabSample(
          sampleId: 'LAB-2024-0891',
          caseId: 'CASE001',
          location: 'Village A, Erode',
          village: 'Veeranam',
          district: 'Erode',
          animalSpecies: 'Cattle',
          suspectedDisease: 'FMD',
          collectedAt: DateTime.now().subtract(const Duration(hours: 6)),
          collectedBy: 'Dr. Rajesh Kumar',
          laboratory: 'Regional Disease Diagnostic Lab, Coimbatore',
          status: LabSampleStatus.inTransit,
          result: LabSampleResult.pending,
        ),
        LabSample(
          sampleId: 'LAB-2024-0890',
          caseId: 'CASE003',
          location: 'Village B, Erode',
          village: 'Kavundampadi',
          district: 'Erode',
          animalSpecies: 'Buffalo',
          suspectedDisease: 'HS',
          collectedAt: DateTime.now().subtract(const Duration(hours: 18)),
          collectedBy: 'Dr. Priya Nair',
          laboratory: 'Regional Disease Diagnostic Lab, Coimbatore',
          status: LabSampleStatus.underTesting,
          result: LabSampleResult.pending,
        ),
        LabSample(
          sampleId: 'LAB-2024-0885',
          caseId: 'CASE002',
          location: 'Village C, Salem',
          village: 'Kolathur',
          district: 'Salem',
          animalSpecies: 'Goat',
          suspectedDisease: 'PPR',
          collectedAt: DateTime.now().subtract(const Duration(days: 2)),
          collectedBy: 'Dr. Anand Sharma',
          laboratory: 'TANUVAS Diagnostic Lab, Chennai',
          status: LabSampleStatus.resultReady,
          result: LabSampleResult.positive,
          resultNotes: 'PPR virus antigen detected by ELISA. Confirmatory PCR pending.',
          resultDate: DateTime.now().subtract(const Duration(hours: 3)),
        ),
        LabSample(
          sampleId: 'LAB-2024-0879',
          caseId: 'CASE004',
          location: 'Village D, Namakkal',
          village: 'Sendamangalam',
          district: 'Namakkal',
          animalSpecies: 'Cattle',
          suspectedDisease: 'BQ',
          collectedAt: DateTime.now().subtract(const Duration(days: 3)),
          collectedBy: 'Dr. Suresh Mohan',
          laboratory: 'Regional Disease Diagnostic Lab, Coimbatore',
          status: LabSampleStatus.completed,
          result: LabSampleResult.negative,
          resultNotes: 'No pathogenic bacteria detected. Likely nutritional deficiency.',
          resultDate: DateTime.now().subtract(const Duration(days: 1)),
        ),
        LabSample(
          sampleId: 'LAB-2024-0871',
          caseId: 'CASE005',
          location: 'Village E, Erode',
          village: 'Anthiyur',
          district: 'Erode',
          animalSpecies: 'Cattle',
          suspectedDisease: 'FMD',
          collectedAt: DateTime.now().subtract(const Duration(days: 5)),
          collectedBy: 'Dr. Rajesh Kumar',
          laboratory: 'Regional Disease Diagnostic Lab, Coimbatore',
          status: LabSampleStatus.completed,
          result: LabSampleResult.positive,
          resultNotes: 'FMD virus serotype O confirmed. Vaccination drive initiated.',
          resultDate: DateTime.now().subtract(const Duration(days: 3)),
        ),
      ];

  // ─── Field Teams ──────────────────────────────────────────────────────────

  static List<FieldTeam> getFieldTeams() => [
        FieldTeam(
          teamId: 'VT-01',
          teamName: 'Erode Rapid Response Team A',
          members: ['Dr. Rajesh Kumar', 'Mr. Senthil Kumar', 'Mr. Arumugam'],
          currentDistrict: 'Erode',
          currentVillage: 'Veeranam',
          currentAssignment: 'FMD outbreak investigation — CASE001',
          status: FieldTeamStatus.onSite,
          lastSync: DateTime.now().subtract(const Duration(minutes: 8)),
          teamType: 'Veterinary',
        ),
        FieldTeam(
          teamId: 'VT-02',
          teamName: 'Erode Vaccination Team B',
          members: ['Dr. Priya Nair', 'Mr. Murugesan'],
          currentDistrict: 'Erode',
          currentVillage: 'Kavundampadi',
          currentAssignment: 'FMD Immunisation Drive — Day 11',
          status: FieldTeamStatus.vaccinating,
          lastSync: DateTime.now().subtract(const Duration(minutes: 22)),
          teamType: 'Vaccination',
        ),
        FieldTeam(
          teamId: 'VT-03',
          teamName: 'Salem Investigation Team',
          members: ['Dr. Anand Sharma', 'Mr. Balasubramanian'],
          currentDistrict: 'Salem',
          currentVillage: 'Kolathur',
          currentAssignment: 'PPR sample collection follow-up',
          status: FieldTeamStatus.investigating,
          lastSync: DateTime.now().subtract(const Duration(minutes: 45)),
          teamType: 'Investigation',
        ),
        FieldTeam(
          teamId: 'VT-04',
          teamName: 'Namakkal Vet Team',
          members: ['Dr. Suresh Mohan', 'Ms. Kavitha'],
          currentDistrict: 'Namakkal',
          currentVillage: 'Namakkal (HQ)',
          currentAssignment: 'No active assignment',
          status: FieldTeamStatus.available,
          lastSync: DateTime.now().subtract(const Duration(minutes: 5)),
          teamType: 'Veterinary',
        ),
        FieldTeam(
          teamId: 'VT-05',
          teamName: 'Erode Mobile Unit C',
          members: ['Dr. Lakshmi', 'Mr. Palani'],
          currentDistrict: 'Erode',
          currentVillage: 'Bhavanisagar',
          currentAssignment: 'FMD Immunisation Drive — Day 11',
          status: FieldTeamStatus.enRoute,
          lastSync: DateTime.now().subtract(const Duration(minutes: 3)),
          teamType: 'Vaccination',
        ),
        FieldTeam(
          teamId: 'VT-06',
          teamName: 'Coimbatore Border Team',
          members: ['Dr. Vikram', 'Mr. Chandran'],
          currentDistrict: 'Coimbatore',
          currentVillage: 'Mettupalayam',
          currentAssignment: 'Movement restriction monitoring',
          status: FieldTeamStatus.offline,
          lastSync: DateTime.now().subtract(const Duration(hours: 2, minutes: 15)),
          teamType: 'Investigation',
        ),
      ];

  // ─── Reports ──────────────────────────────────────────────────────────────

  static List<GovtReport> getReports() {
    final now = DateTime.now();
    return [
      GovtReport(
        reportId: 'RPT-2024-0901',
        category: ReportCategory.dailySurveillance,
        title: 'Daily Surveillance Report — ${now.day}/${now.month}/${now.year}',
        reportDate: now,
        coverage: 'Erode, Namakkal, Salem, Coimbatore districts',
        generatedBy: 'System (Auto-generated)',
        status: ReportStatus.ready,
      ),
      GovtReport(
        reportId: 'RPT-2024-0897',
        category: ReportCategory.weeklyDiseaseSummary,
        title: 'Weekly Disease Summary — Week ${_weekNumber(now)}',
        reportDate: now.subtract(const Duration(days: 1)),
        coverage: 'Tamil Nadu State',
        generatedBy: 'Dr. K. Murugan, DAHO',
        status: ReportStatus.ready,
      ),
      GovtReport(
        reportId: 'RPT-2024-0893',
        category: ReportCategory.outbreakReport,
        title: 'FMD Suspected Outbreak — Erode District',
        reportDate: now.subtract(const Duration(days: 2)),
        coverage: 'Erode District — 5 villages',
        generatedBy: 'Dr. Rajesh Kumar, Field Officer',
        status: ReportStatus.ready,
      ),
      GovtReport(
        reportId: 'RPT-2024-0888',
        category: ReportCategory.vaccinationReport,
        title: 'FMD Campaign Progress Report — Week 2',
        reportDate: now.subtract(const Duration(days: 3)),
        coverage: 'Erode District — FMD Immunisation Drive',
        generatedBy: 'Vaccination Cell, DAHO Erode',
        status: ReportStatus.ready,
      ),
      GovtReport(
        reportId: 'RPT-2024-0882',
        category: ReportCategory.mortalityReport,
        title: 'Monthly Mortality Analysis — August 2024',
        reportDate: now.subtract(const Duration(days: 7)),
        coverage: 'Erode, Namakkal, Salem',
        generatedBy: 'System (Auto-generated)',
        status: ReportStatus.ready,
      ),
      GovtReport(
        reportId: 'RPT-2024-0875',
        category: ReportCategory.laboratoryReport,
        title: 'Laboratory Status Report — September W1',
        reportDate: now.subtract(const Duration(days: 8)),
        coverage: 'RDDL Coimbatore, TANUVAS Chennai',
        generatedBy: 'Laboratory Surveillance Cell',
        status: ReportStatus.ready,
      ),
      GovtReport(
        reportId: 'RPT-2024-0869',
        category: ReportCategory.districtHealthReport,
        title: 'District Animal Health Status — Erode Q2',
        reportDate: now.subtract(const Duration(days: 15)),
        coverage: 'Erode District — All Blocks',
        generatedBy: 'DAHO Erode',
        status: ReportStatus.ready,
      ),
    ];
  }

  static int _weekNumber(DateTime date) {
    final firstDayOfYear = DateTime(date.year, 1, 1);
    return ((date.difference(firstDayOfYear).inDays + firstDayOfYear.weekday) / 7).ceil();
  }

  // ─── Aggregate stats for Command Center ───────────────────────────────────

  static GovernmentStats getExecutiveStats() => const GovernmentStats(
        activeCases: 27,
        activeCasesTrend: '↑ 5 today',
        highRiskZones: 3,
        highRiskZonesTrend: '+1 detected',
        suspectedOutbreaks: 5,
        suspectedOutbreaksCritical: 2,
        animalsMonitored: 12540,
        animalsMonitoredTrend: '+420 this week',
        vaccinationCoveragePercent: 76,
        vaccinationTargetPercent: 90,
        labSamplesPending: 12,
        labSamplesTesting: 5,
        districtHealthStatus: 'HIGH ALERT',
        lastSyncMinutesAgo: '2 min ago',
      );

  static Map<String, dynamic> getCommandCenterStats() => {
        'highRiskZones': 3,
        'highRiskZonesNew': 1,
        'activeCases': 27,
        'activeCasesNew': 5,
        'suspectedOutbreaks': 5,
        'suspectedOutbreaksCritical': 2,
        'animalsMonitored': 12540,
        'animalsMonitoredChange': '+4.2%',
        'systemStatus': 'All surveillance services operational',
        'lastSync': '2 min ago',
        'jurisdiction': 'Erode District',
      };

  // ─── Geospatial Risk Zones ───────────────────────────────────────────────

  static List<RiskZone> getRiskZonesList() => const [
        RiskZone(
          id: 'RZ-01',
          village: 'Perundurai (Village A)',
          block: 'Perundurai',
          district: 'Erode',
          riskLevel: 'CRITICAL',
          activeCases: 12,
          mortality: 2,
          vaccinationCoverage: 61,
          lastReportAgo: '18 min ago',
          possibleDisease: 'FMD',
          normX: 0.38,
          normY: 0.44,
          trendPercent: 32,
          trendDirection: 'up',
          contributingFactors: [
            '12 active fever & vesicle reports in 48h',
            'Low vaccination coverage (61%)',
            'Water stagnation along Bhavani tributary',
          ],
        ),
        RiskZone(
          id: 'RZ-02',
          village: 'Bhavani (Village C)',
          block: 'Bhavani',
          district: 'Erode',
          riskLevel: 'HIGH',
          activeCases: 8,
          mortality: 1,
          vaccinationCoverage: 68,
          lastReportAgo: '35 min ago',
          possibleDisease: 'HS',
          normX: 0.60,
          normY: 0.30,
          trendPercent: 15,
          trendDirection: 'up',
          contributingFactors: [
            'High respiratory distress index',
            'Cattle transit corridor border',
          ],
        ),
        RiskZone(
          id: 'RZ-03',
          village: 'Gobichettipalayam (Village F)',
          block: 'Gobi',
          district: 'Erode',
          riskLevel: 'MODERATE',
          activeCases: 5,
          mortality: 0,
          vaccinationCoverage: 74,
          lastReportAgo: '1 hour ago',
          possibleDisease: 'BQ',
          normX: 0.25,
          normY: 0.25,
          trendPercent: 0,
          trendDirection: 'stable',
          contributingFactors: ['Scattered mild lameness in 5 cattle'],
        ),
        RiskZone(
          id: 'RZ-04',
          village: 'Kavundampadi (Village B)',
          block: 'Bhavani',
          district: 'Erode',
          riskLevel: 'MODERATE',
          activeCases: 4,
          mortality: 0,
          vaccinationCoverage: 71,
          lastReportAgo: '2 hours ago',
          possibleDisease: 'FMD',
          normX: 0.48,
          normY: 0.36,
          trendPercent: 5,
          trendDirection: 'down',
        ),
        RiskZone(
          id: 'RZ-05',
          village: 'Anthiyur',
          block: 'Anthiyur',
          district: 'Erode',
          riskLevel: 'HIGH',
          activeCases: 4,
          mortality: 1,
          vaccinationCoverage: 69,
          lastReportAgo: '3 hours ago',
          possibleDisease: 'Anthrax',
          normX: 0.50,
          normY: 0.16,
          trendPercent: 10,
          trendDirection: 'up',
        ),
        RiskZone(
          id: 'RZ-06',
          village: 'Chennimalai',
          block: 'Perundurai',
          district: 'Erode',
          riskLevel: 'MODERATE',
          activeCases: 2,
          mortality: 0,
          vaccinationCoverage: 75,
          lastReportAgo: '4 hours ago',
          possibleDisease: 'FMD',
          normX: 0.32,
          normY: 0.70,
          trendPercent: 0,
          trendDirection: 'stable',
        ),
        RiskZone(
          id: 'RZ-07',
          village: 'Sathyamangalam',
          block: 'Sathyamangalam',
          district: 'Erode',
          riskLevel: 'LOW',
          activeCases: 1,
          mortality: 0,
          vaccinationCoverage: 88,
          lastReportAgo: '4 hours ago',
          possibleDisease: 'LSD',
          normX: 0.18,
          normY: 0.52,
          trendPercent: 12,
          trendDirection: 'down',
        ),
        RiskZone(
          id: 'RZ-08',
          village: 'Modakkurichi',
          block: 'Modakkurichi',
          district: 'Erode',
          riskLevel: 'LOW',
          activeCases: 1,
          mortality: 0,
          vaccinationCoverage: 84,
          lastReportAgo: '5 hours ago',
          possibleDisease: 'None',
          normX: 0.65,
          normY: 0.62,
          trendPercent: 0,
          trendDirection: 'stable',
        ),
        RiskZone(
          id: 'RZ-09',
          village: 'Kodumudi',
          block: 'Kodumudi',
          district: 'Erode',
          riskLevel: 'LOW',
          activeCases: 0,
          mortality: 0,
          vaccinationCoverage: 92,
          lastReportAgo: '6 hours ago',
          possibleDisease: 'None',
          normX: 0.76,
          normY: 0.80,
          trendPercent: 20,
          trendDirection: 'down',
        ),
      ];

  // ─── Outbreak Records ───────────────────────────────────────────────────

  static List<OutbreakRecord> getOutbreakRecords() => [
        OutbreakRecord(
          id: 'OB-024',
          title: 'Suspected FMD Cluster',
          village: 'Village A (Perundurai)',
          district: 'Erode',
          affectedAnimals: 12,
          mortality: 2,
          confidencePercent: 87,
          status: 'UNDER INVESTIGATION',
          suspectedDisease: 'Foot-and-Mouth Disease (FMD)',
          riskSeverity: 'CRITICAL',
          detectedAt: DateTime.now().subtract(const Duration(hours: 4)),
          assignedTeams: ['Team Alpha (VT-01)'],
        ),
        OutbreakRecord(
          id: 'OB-023',
          title: 'Haemorrhagic Septicaemia Cluster',
          village: 'Village C (Bhavani)',
          district: 'Erode',
          affectedAnimals: 7,
          mortality: 1,
          confidencePercent: 92,
          status: 'FIELD RESPONSE ACTIVE',
          suspectedDisease: 'Haemorrhagic Septicaemia (HS)',
          riskSeverity: 'HIGH',
          detectedAt: DateTime.now().subtract(const Duration(hours: 14)),
          assignedTeams: ['Team Bravo (VT-02)'],
        ),
        OutbreakRecord(
          id: 'OB-022',
          title: 'Anthrax Surveillance Ring',
          village: 'Anthiyur Foothills',
          district: 'Erode',
          affectedAnimals: 4,
          mortality: 1,
          confidencePercent: 78,
          status: 'UNDER INVESTIGATION',
          suspectedDisease: 'Anthrax',
          riskSeverity: 'HIGH',
          detectedAt: DateTime.now().subtract(const Duration(days: 1, hours: 2)),
          assignedTeams: ['Team Charlie (VT-03)'],
        ),
        OutbreakRecord(
          id: 'OB-021',
          title: 'Lumpy Skin Disease Pocket',
          village: 'Sathyamangalam',
          district: 'Erode',
          affectedAnimals: 3,
          mortality: 0,
          confidencePercent: 95,
          status: 'CONTAINED',
          suspectedDisease: 'Lumpy Skin Disease (LSD)',
          riskSeverity: 'MODERATE',
          detectedAt: DateTime.now().subtract(const Duration(days: 3)),
          assignedTeams: ['Team Delta (VT-04)'],
        ),
      ];

  // ─── Government Alerts ──────────────────────────────────────────────────

  static List<GovernmentAlert> getGovernmentAlerts() => [
        GovernmentAlert(
          id: 'ALT-001',
          category: 'CRITICAL',
          title: 'New suspected outbreak detected',
          location: 'Village A (Perundurai)',
          timeAgo: '8 minutes ago',
          description: '12 cattle reported with high fever, salivation, and oral vesicles within a 2 km radius.',
        ),
        GovernmentAlert(
          id: 'ALT-002',
          category: 'HIGH',
          title: 'Vaccination coverage below target',
          location: 'Village F (Gobichettipalayam)',
          timeAgo: '32 minutes ago',
          description: 'FMD vaccination coverage currently at 61% against 90% district mandate. Immediate ring drive advised.',
        ),
        GovernmentAlert(
          id: 'ALT-003',
          category: 'ADVISORY',
          title: 'Heavy rainfall may increase disease risk',
          location: 'District-wide (Erode)',
          timeAgo: '1 hour ago',
          description: 'IMD predicts 65mm precipitation over the next 48h. Water stagnation accelerates vector breeding and HS spread.',
        ),
        GovernmentAlert(
          id: 'ALT-004',
          category: 'SYSTEM',
          title: 'Laboratory sync completed',
          location: 'TANUVAS Regional Lab',
          timeAgo: '2 hours ago',
          description: '5 diagnostic test batches synchronized into the state surveillance registry.',
        ),
      ];

  // ─── Vaccination Intelligence Stats ─────────────────────────────────────

  static VaccinationStats getVaccinationIntelligence() => const VaccinationStats(
        overallCoveragePercent: 76,
        targetCoveragePercent: 90,
        vaccinatedAnimals: 38000,
        pendingAnimals: 12000,
        districtCoverage: {
          'ERODE': 76,
          'TIRUPPUR': 82,
          'SALEM': 69,
          'NAMAKKAL': 88,
        },
        priorityZones: [
          'Perundurai Block (61% coverage)',
          'Bhavani North (68% coverage)',
          'Anthiyur Foothills (69% coverage)',
        ],
      );

  // ─── Multi-Timeframe Disease Trend Points ────────────────────────────────

  static List<DiseaseTrendPoint> getDiseaseTrendPoints(String timeframe) {
    switch (timeframe) {
      case '30 DAYS':
        return const [
          DiseaseTrendPoint(label: 'W1', cases: 14, mortality: 2, recovery: 10, disease: 'FMD', location: 'Perundurai'),
          DiseaseTrendPoint(label: 'W2', cases: 19, mortality: 3, recovery: 14, disease: 'FMD', location: 'Bhavani'),
          DiseaseTrendPoint(label: 'W3', cases: 24, mortality: 4, recovery: 18, disease: 'FMD/HS', location: 'Erode East'),
          DiseaseTrendPoint(label: 'W4', cases: 27, mortality: 3, recovery: 22, disease: 'FMD', location: 'District-wide'),
        ];
      case '3 MONTHS':
        return const [
          DiseaseTrendPoint(label: 'Jun', cases: 58, mortality: 9, recovery: 48, disease: 'LSD', location: 'District-wide'),
          DiseaseTrendPoint(label: 'Jul', cases: 42, mortality: 5, recovery: 38, disease: 'HS', location: 'District-wide'),
          DiseaseTrendPoint(label: 'Aug', cases: 79, mortality: 11, recovery: 62, disease: 'FMD', location: 'District-wide'),
        ];
      case '1 YEAR':
        return const [
          DiseaseTrendPoint(label: 'Q1', cases: 140, mortality: 22, recovery: 120, disease: 'Seasonal Peak', location: 'State'),
          DiseaseTrendPoint(label: 'Q2', cases: 85, mortality: 10, recovery: 74, disease: 'Controlled', location: 'State'),
          DiseaseTrendPoint(label: 'Q3', cases: 112, mortality: 18, recovery: 96, disease: 'Monsoon Spike', location: 'State'),
          DiseaseTrendPoint(label: 'Q4', cases: 94, mortality: 12, recovery: 82, disease: 'Post-drive', location: 'State'),
        ];
      case '7 DAYS':
      default:
        return const [
          DiseaseTrendPoint(label: 'Mon', cases: 15, mortality: 1, recovery: 12, disease: 'FMD', location: 'Perundurai'),
          DiseaseTrendPoint(label: 'Tue', cases: 18, mortality: 2, recovery: 14, disease: 'FMD', location: 'Bhavani'),
          DiseaseTrendPoint(label: 'Wed', cases: 16, mortality: 1, recovery: 15, disease: 'HS', location: 'Gobi'),
          DiseaseTrendPoint(label: 'Thu', cases: 22, mortality: 3, recovery: 17, disease: 'FMD', location: 'Perundurai'),
          DiseaseTrendPoint(label: 'Fri', cases: 24, mortality: 2, recovery: 19, disease: 'FMD', location: 'Anthiyur'),
          DiseaseTrendPoint(label: 'Sat', cases: 28, mortality: 4, recovery: 21, disease: 'FMD/HS', location: 'District-wide'),
          DiseaseTrendPoint(label: 'Sun', cases: 27, mortality: 3, recovery: 24, disease: 'FMD', location: 'District-wide'),
        ];
    }
  }

  // ─── Outbreak trend data (7-day legacy compat) ───────────────────────────

  static List<Map<String, dynamic>> getOutbreakTrendData() => [
        {'day': 'Mon', 'current': 3, 'previous': 5},
        {'day': 'Tue', 'current': 5, 'previous': 4},
        {'day': 'Wed', 'current': 4, 'previous': 6},
        {'day': 'Thu', 'current': 7, 'previous': 5},
        {'day': 'Fri', 'current': 6, 'previous': 3},
        {'day': 'Sat', 'current': 9, 'previous': 4},
        {'day': 'Sun', 'current': 8, 'previous': 7},
      ];

  // ─── Risk Intelligence data ───────────────────────────────────────────────

  static Map<String, dynamic> getRiskIntelligence() => {
        'riskLevel': 'HIGH',
        'confidence': 87,
        'trend': 'Increasing',
        'lastUpdated': '18 min ago',
        'contributingFactors': [
          '34% increase in fever-related reports across 3 nearby villages',
          'Reduced vaccination coverage in Perundurai corridor (61%)',
          'Unseasonal precipitation and high relative humidity (84%)',
          'Geographic clustering of reports within 5 km radius',
        ],
        'riskZones': [
          {'name': 'Perundurai (Village A)', 'risk': 'CRITICAL', 'cases': 12, 'trend': '↑ 32%'},
          {'name': 'Bhavani (Village C)', 'risk': 'HIGH', 'cases': 8, 'trend': '↑ 15%'},
          {'name': 'Gobichettipalayam (Village F)', 'risk': 'MODERATE', 'cases': 5, 'trend': '→ stable'},
          {'name': 'Kavundampadi (Village B)', 'risk': 'MODERATE', 'cases': 4, 'trend': '↓ 5%'},
          {'name': 'Anthiyur', 'risk': 'HIGH', 'cases': 4, 'trend': '↑ 10%'},
          {'name': 'Sathyamangalam', 'risk': 'LOW', 'cases': 1, 'trend': '↓ 12%'},
          {'name': 'Modakkurichi', 'risk': 'LOW', 'cases': 1, 'trend': '→ stable'},
        ],
      };

  // ─── India States Surveillance Risk Profiles (National Map) ──────────────

  static List<StateRiskProfile> getIndiaStatesRiskProfiles() => const [
        StateRiskProfile(
          code: 'TN',
          name: 'Tamil Nadu',
          riskScore: 82,
          riskLevel: 'CRITICAL',
          activeCases: 1284,
          suspectedOutbreaks: 7,
          confirmedOutbreaks: 3,
          mortality: 86,
          vaccinationCoverage: 74,
          dominantDisease: 'Foot-and-Mouth Disease',
          trendPercent: 18,
          trendDirection: 'up',
          riskDrivers: [
            'Increasing case reports in Western corridor (+18%)',
            'Low vaccination coverage in 3 blocks (under 65%)',
            'Unseasonal rainfall along Bhavani river basin',
            'High livestock density (380 head / sq km)',
          ],
          recommendedAction: 'Enhanced surveillance & barrier cordoning recommended',
          normX: 0.44,
          normY: 0.84,
          districts: [
            DistrictRiskProfile(name: 'Erode', state: 'Tamil Nadu', riskScore: 92, riskLevel: 'Critical', cases: 48, mortality: 6, vaccinationCoverage: 76, trend: '↑ 24%'),
            DistrictRiskProfile(name: 'Salem', state: 'Tamil Nadu', riskScore: 84, riskLevel: 'Critical', cases: 36, mortality: 4, vaccinationCoverage: 69, trend: '↑ 18%'),
            DistrictRiskProfile(name: 'Coimbatore', state: 'Tamil Nadu', riskScore: 71, riskLevel: 'High', cases: 22, mortality: 2, vaccinationCoverage: 82, trend: '↑ 8%'),
            DistrictRiskProfile(name: 'Namakkal', state: 'Tamil Nadu', riskScore: 63, riskLevel: 'High', cases: 19, mortality: 1, vaccinationCoverage: 88, trend: '↓ 5%'),
            DistrictRiskProfile(name: 'Tiruppur', state: 'Tamil Nadu', riskScore: 58, riskLevel: 'Moderate', cases: 14, mortality: 0, vaccinationCoverage: 85, trend: '→ stable'),
          ],
        ),
        StateRiskProfile(
          code: 'KA',
          name: 'Karnataka',
          riskScore: 76,
          riskLevel: 'HIGH',
          activeCases: 942,
          suspectedOutbreaks: 5,
          confirmedOutbreaks: 2,
          mortality: 54,
          vaccinationCoverage: 78,
          dominantDisease: 'Anthrax & HS',
          trendPercent: 12,
          trendDirection: 'up',
          riskDrivers: [
            'Inter-state cattle transit along NH-44',
            'High soil spore persistence in Chamrajnagar',
            'Delayed vaccination schedule in rural taluks',
          ],
          recommendedAction: 'Intensify border checkposts and quarantine verification',
          normX: 0.36,
          normY: 0.72,
          districts: [
            DistrictRiskProfile(name: 'Mysuru', state: 'Karnataka', riskScore: 78, riskLevel: 'High', cases: 32, mortality: 3, vaccinationCoverage: 74, trend: '↑ 14%'),
            DistrictRiskProfile(name: 'Mandya', state: 'Karnataka', riskScore: 72, riskLevel: 'High', cases: 26, mortality: 2, vaccinationCoverage: 79, trend: '↑ 9%'),
          ],
        ),
        StateRiskProfile(
          code: 'AP',
          name: 'Andhra Pradesh',
          riskScore: 68,
          riskLevel: 'HIGH',
          activeCases: 810,
          suspectedOutbreaks: 4,
          confirmedOutbreaks: 2,
          mortality: 42,
          vaccinationCoverage: 81,
          dominantDisease: 'Brucellosis & FMD',
          trendPercent: 9,
          trendDirection: 'up',
          riskDrivers: [
            'Dairy farm cluster density in Krishna delta',
            'Delayed syndromic alerts from private dairies',
          ],
          recommendedAction: 'Deploy mobile ring testing units to Krishna basin',
          normX: 0.50,
          normY: 0.68,
        ),
        StateRiskProfile(
          code: 'KL',
          name: 'Kerala',
          riskScore: 51,
          riskLevel: 'MODERATE',
          activeCases: 380,
          suspectedOutbreaks: 2,
          confirmedOutbreaks: 1,
          mortality: 14,
          vaccinationCoverage: 86,
          dominantDisease: 'Lumpy Skin Disease',
          trendPercent: 4,
          trendDirection: 'down',
          riskDrivers: [
            'High vector humidity along Western Ghats',
            'Wildlife corridor buffer interaction',
          ],
          recommendedAction: 'Maintain biosecurity along wildlife buffer zones',
          normX: 0.38,
          normY: 0.90,
        ),
        StateRiskProfile(
          code: 'TG',
          name: 'Telangana',
          riskScore: 44,
          riskLevel: 'MODERATE',
          activeCases: 310,
          suspectedOutbreaks: 2,
          confirmedOutbreaks: 1,
          mortality: 12,
          vaccinationCoverage: 84,
          dominantDisease: 'PPR in Small Ruminants',
          trendPercent: 2,
          trendDirection: 'down',
          riskDrivers: ['Seasonal pastoral sheep transit'],
          recommendedAction: 'Continue migratory flock ring vaccination',
          normX: 0.46,
          normY: 0.60,
        ),
        StateRiskProfile(
          code: 'MH',
          name: 'Maharashtra',
          riskScore: 72,
          riskLevel: 'HIGH',
          activeCases: 1120,
          suspectedOutbreaks: 6,
          confirmedOutbreaks: 2,
          mortality: 68,
          vaccinationCoverage: 73,
          dominantDisease: 'FMD & Black Quarter (BQ)',
          trendPercent: 15,
          trendDirection: 'up',
          riskDrivers: [
            'Cattle fair congregate events',
            'Transit corridors connecting Gujarat & MP',
          ],
          recommendedAction: 'Suspend weekly cattle markets in Marathwada',
          normX: 0.34,
          normY: 0.52,
        ),
        StateRiskProfile(
          code: 'UP',
          name: 'Uttar Pradesh',
          riskScore: 85,
          riskLevel: 'CRITICAL',
          activeCases: 2150,
          suspectedOutbreaks: 11,
          confirmedOutbreaks: 5,
          mortality: 142,
          vaccinationCoverage: 66,
          dominantDisease: 'Haemorrhagic Septicaemia (HS)',
          trendPercent: 26,
          trendDirection: 'up',
          riskDrivers: [
            'Water stagnation along Gangetic floodplains',
            'Dense buffalo dairy concentrations',
            'Severe vaccination shortfall in eastern districts',
          ],
          recommendedAction: 'Immediate emergency antibiotic & HS ring vaccination drive',
          normX: 0.52,
          normY: 0.32,
        ),
        StateRiskProfile(
          code: 'GJ',
          name: 'Gujarat',
          riskScore: 48,
          riskLevel: 'MODERATE',
          activeCases: 420,
          suspectedOutbreaks: 2,
          confirmedOutbreaks: 1,
          mortality: 18,
          vaccinationCoverage: 89,
          dominantDisease: 'LSD & Brucellosis',
          trendPercent: 8,
          trendDirection: 'down',
          riskDrivers: ['Dry weather reducing vector loads'],
          recommendedAction: 'Sustain cooperative dairy vaccination compliance',
          normX: 0.20,
          normY: 0.44,
        ),
        StateRiskProfile(
          code: 'RJ',
          name: 'Rajasthan',
          riskScore: 58,
          riskLevel: 'MODERATE',
          activeCases: 560,
          suspectedOutbreaks: 3,
          confirmedOutbreaks: 1,
          mortality: 22,
          vaccinationCoverage: 79,
          dominantDisease: 'Sheep Pox & Enterotoxemia',
          trendPercent: 5,
          trendDirection: 'up',
          riskDrivers: ['Nomadic pastoral herds moving to pastures'],
          recommendedAction: 'Deploy mobile veterinary dispensaries to transit routes',
          normX: 0.28,
          normY: 0.32,
        ),
        StateRiskProfile(
          code: 'WB',
          name: 'West Bengal',
          riskScore: 64,
          riskLevel: 'HIGH',
          activeCases: 690,
          suspectedOutbreaks: 4,
          confirmedOutbreaks: 2,
          mortality: 38,
          vaccinationCoverage: 71,
          dominantDisease: 'PPR & Duck Plague',
          trendPercent: 11,
          trendDirection: 'up',
          riskDrivers: [
            'Wetland vector density',
            'Border livestock movement',
          ],
          recommendedAction: 'Intensify riverine veterinary monitoring posts',
          normX: 0.74,
          normY: 0.44,
        ),
      ];

  // ─── "Why is this area at risk?" Intelligence Analysis ────────────────────

  static WhyRiskHighAnalysis getWhyRiskHigh(String areaName) {
    return const WhyRiskHighAnalysis(
      areaName: 'Erode District',
      riskScore: 87,
      riskLevel: 'CRITICAL',
      dominantDisease: 'FMD',
      trend: '↑ 23%',
      conciseReasons: [
        '↑ 31% symptom reports',
        '↓ 14% vaccination coverage',
        '🌧 Heavy rainfall',
        '🐄 High livestock density',
      ],
      contributors: [
        RiskContributor('Symptom reports', 92, '+31% surge in syndromic fever & vesicle reports in 48h'),
        RiskContributor('Mortality trend', 81, '+18% elevation in adult dairy cow case fatality'),
        RiskContributor('Vaccination gap', 72, '14% drop in coverage; 61% vs 90% district target'),
        RiskContributor('Weather conditions', 84, 'Unseasonal heavy precipitation (+28%) & humidity (+16%)'),
        RiskContributor('Livestock density', 89, '380 head per sq km in high-density Perundurai belt'),
        RiskContributor('Historical recurrence', 78, 'Cluster area had FMD outbreak during Sep-Oct historically'),
      ],
      recommendedAction: 'Immediate veterinary surveillance and targeted vaccination recommended.',
    );
  }

  // ─── Outbreak Incidents with Complete Workflow & Response Checklist ───────

  static List<OutbreakIncident> getOutbreakIncidents() => [
        const OutbreakIncident(
          clusterId: 'OB-024',
          disease: 'FMD',
          location: 'Erode',
          cases: 146,
          mortality: 18,
          trend: '↑ 23%',
          status: 'Investigating',
          firstDetectedAgo: '02 Sep (4 days ago)',
          riskScore: 87,
          riskLevel: 'CRITICAL',
          currentStep: OutbreakWorkflowStep.investigating,
          assignedTeam: 'Team V-024 (Dr. Rajesh Kumar)',
          affectedVillages: ['Veeranam', 'Kavundampadi', 'Perundurai East', 'Bhavani South', 'Ingur', 'Chennimalai', 'Vijayamangalam'],
          vaccinationCoverage: 61,
          labStatus: 'Testing at TANUVAS Regional Lab',
          timeline: {
            'First Report': '02 Sep',
            'Cluster Detected': '04 Sep',
            'Veterinarian Assigned': '05 Sep',
            'Sample Submitted': '06 Sep',
            'Current Status': 'Investigation',
          },
          responseChecklist: [
            OutbreakResponseActionItem('Assign veterinary team (Team V-024)', 'Completed'),
            OutbreakResponseActionItem('Collect oral vesicle & epithelial scrapings', 'Completed'),
            OutbreakResponseActionItem('Notify district collector & animal husbandry director', 'Completed'),
            OutbreakResponseActionItem('Issue livestock-owner containment advisory', 'Completed'),
            OutbreakResponseActionItem('Review vaccination status of 5 km ring buffer', 'In Progress'),
            OutbreakResponseActionItem('Monitor nearby villages (Bhavani, Kavundampadi)', 'In Progress'),
            OutbreakResponseActionItem('Track laboratory confirmation from TANUVAS', 'In Progress'),
            OutbreakResponseActionItem('Update containment status & movement restrictions', 'Pending'),
          ],
        ),
        const OutbreakIncident(
          clusterId: 'OB-019',
          disease: 'PPR',
          location: 'Salem',
          cases: 87,
          mortality: 7,
          trend: '↑ 12%',
          status: 'Containment',
          firstDetectedAgo: '01 Sep (5 days ago)',
          riskScore: 74,
          riskLevel: 'HIGH',
          currentStep: OutbreakWorkflowStep.containmentActive,
          assignedTeam: 'Team V-011 (Dr. Priya S.)',
          affectedVillages: ['Omalur', 'Mecheri', 'Kadayampatti', 'Jalakandapuram'],
          vaccinationCoverage: 68,
          labStatus: 'Result Confirmed Positive (PPR Lineage IV)',
          timeline: {
            'First Report': '01 Sep',
            'Cluster Detected': '03 Sep',
            'Veterinarian Assigned': '03 Sep',
            'Sample Submitted': '04 Sep',
            'Current Status': 'Containment Active',
          },
          responseChecklist: [
            OutbreakResponseActionItem('Assign veterinary rapid team', 'Completed'),
            OutbreakResponseActionItem('Collect ocular/nasal swabs', 'Completed'),
            OutbreakResponseActionItem('Notify Salem animal husbandry directorate', 'Completed'),
            OutbreakResponseActionItem('Issue small-ruminant quarantine advisory', 'Completed'),
            OutbreakResponseActionItem('Execute 5km ring vaccination campaign', 'In Progress'),
            OutbreakResponseActionItem('Monitor weekly livestock shandy transit', 'In Progress'),
          ],
        ),
        const OutbreakIncident(
          clusterId: 'OB-017',
          disease: 'Anthrax',
          location: 'Coimbatore',
          cases: 34,
          mortality: 4,
          trend: '↓ 5%',
          status: 'Monitoring',
          firstDetectedAgo: '28 Aug (9 days ago)',
          riskScore: 48,
          riskLevel: 'MODERATE',
          currentStep: OutbreakWorkflowStep.monitoring,
          assignedTeam: 'Team V-008 (Dr. Anand M.)',
          affectedVillages: ['Pollachi North', 'Kinathukadavu', 'Anaimalai Foothills'],
          vaccinationCoverage: 84,
          labStatus: 'Microscopy Confirmed (Bacillus anthracis)',
          timeline: {
            'First Report': '28 Aug',
            'Cluster Detected': '29 Aug',
            'Veterinarian Assigned': '29 Aug',
            'Sample Submitted': '30 Aug',
            'Current Status': 'Monitoring & Cordon',
          },
          responseChecklist: [
            OutbreakResponseActionItem('Enforce deep carcass burial with quicklime', 'Completed'),
            OutbreakResponseActionItem('Quarantine spore contamination zone', 'Completed'),
            OutbreakResponseActionItem('Administer spore vaccine to surrounding herds', 'Completed'),
            OutbreakResponseActionItem('Monitor pasture safety for 21 days', 'In Progress'),
          ],
        ),
        const OutbreakIncident(
          clusterId: 'OB-012',
          disease: 'LSD',
          location: 'Tiruppur',
          cases: 62,
          mortality: 5,
          trend: '↑ 8%',
          status: 'Sample Collected',
          firstDetectedAgo: '03 Sep (3 days ago)',
          riskScore: 69,
          riskLevel: 'HIGH',
          currentStep: OutbreakWorkflowStep.sampleCollected,
          assignedTeam: 'Team V-015 (Dr. K. Murugan)',
          affectedVillages: ['Dharapuram', 'Kangeyam', 'Uthukuli'],
          vaccinationCoverage: 71,
          labStatus: 'Samples dispatced to TANUVAS',
          timeline: {
            'First Report': '03 Sep',
            'Cluster Detected': '04 Sep',
            'Veterinarian Assigned': '05 Sep',
            'Sample Submitted': '06 Sep',
            'Current Status': 'Sample Testing',
          },
          responseChecklist: [
            OutbreakResponseActionItem('Assign veterinary inspection squad', 'Completed'),
            OutbreakResponseActionItem('Collect nodular skin biopsies & blood samples', 'Completed'),
            OutbreakResponseActionItem('Notify Tiruppur veterinary dispensary', 'Completed'),
            OutbreakResponseActionItem('Vector control fogging & insecticide spray', 'In Progress'),
            OutbreakResponseActionItem('Screen nearby Kangeyam breed herds', 'Pending'),
          ],
        ),
      ];

  // ─── Early Warning Notices ────────────────────────────────────────────────

  static List<EarlyWarningNotice> getEarlyWarnings() => [
        EarlyWarningNotice(
          id: '#EW-018',
          headline: 'Rapid increase in cattle fever reports detected in Erode Block',
          location: 'Perundurai & Bhavani Corridor, Erode',
          confidence: 'High (87%)',
          supportingSignals: const [
            '+31% reports in 72 hours (48 animals displaying pyrexia & salivation)',
            '+12% mortality in adult dairy cows over 48h',
            'Vaccination coverage 61% below 90% district mandate',
            'Recent unseasonal rainfall (+24mm) creating humidity spike',
          ],
          recommendedAction: 'Deploy field veterinary surveillance team & initiate barrier quarantine.',
          timestamp: DateTime.now().subtract(const Duration(minutes: 38)),
        ),
        EarlyWarningNotice(
          id: '#EW-017',
          headline: 'Unseasonal precipitation correlation with HS vector risk',
          location: 'Gangetic Plains, Uttar Pradesh',
          confidence: 'High (92%)',
          supportingSignals: const [
            '+65mm rainfall resulting in localized pasture water stagnation',
            'Historical HS incidence spike correlation in Sep-Oct',
            'Vaccination shortfall in eastern districts (66% coverage)',
          ],
          recommendedAction: 'Pre-position emergency antibiotics & dispatch HS ring vaccination teams.',
          timestamp: DateTime.now().subtract(const Duration(hours: 2)),
        ),
      ];

  // ─── System Health & Connectivity Metrics ─────────────────────────────────

  static DataHealthMetrics getDataHealthMetrics() => const DataHealthMetrics(
        reportsReceived: 1420,
        incompleteReports: 18,
        duplicateReports: 7,
        missingVaccinationRecords: 34,
        pendingLabResults: 12,
        offlineSubmissionsWaiting: 34,
      );

  static FieldConnectivityMetrics getConnectivityMetrics() => const FieldConnectivityMetrics(
        onlinePercent: 82,
        offlinePercent: 18,
        pendingSyncCount: 34,
        lastSyncTime: '2 minutes ago',
      );

  static ResponseTimeMetrics getResponseTimeMetrics() => const ResponseTimeMetrics(
        reportingTimeHours: 4.2,
        responseTimeHours: 1.8,
        labTurnaroundHours: 14.5,
        containmentDays: 3.2,
      );

  // ─── Maharashtra District Surveillance Intelligence ───────────────────────

  static List<DistrictRiskProfile> getMaharashtraDistricts() => const [
        DistrictRiskProfile(
          name: 'Nagpur',
          state: 'Maharashtra',
          riskScore: 81,
          riskLevel: 'CRITICAL',
          cases: 64,
          mortality: 8,
          vaccinationCoverage: 61,
          trend: '↑ 18%',
          primaryDisease: 'FMD',
          whyHighRisk: [
            'Increasing reported cases in pastoral clusters',
            'Rising mortality in unimmunized crossbred cattle',
            'Low vaccination coverage (61%) below 85% mandate',
            'Recent historical pattern & seasonal humidity spike',
          ],
          recommendedAction: 'Prioritize field investigation and vaccination response.',
          normX: 0.82,
          normY: 0.22,
        ),
        DistrictRiskProfile(
          name: 'Amravati',
          state: 'Maharashtra',
          riskScore: 72,
          riskLevel: 'HIGH',
          cases: 52,
          mortality: 5,
          vaccinationCoverage: 64,
          trend: '↑ 14%',
          primaryDisease: 'FMD',
          whyHighRisk: [
            'Cross-district animal movement from Vidarbha borders',
            'Cluster symptom surge in 3 rural blocks',
            'Vaccination backlog in smallholder dairy farms',
            'Pasture water pooling post unseasonal rain',
          ],
          recommendedAction: 'Deploy 5km ring vaccination and enforce movement checkpost.',
          normX: 0.65,
          normY: 0.20,
        ),
        DistrictRiskProfile(
          name: 'Nashik',
          state: 'Maharashtra',
          riskScore: 68,
          riskLevel: 'HIGH',
          cases: 48,
          mortality: 4,
          vaccinationCoverage: 70,
          trend: '↑ 12%',
          primaryDisease: 'Brucellosis',
          whyHighRisk: [
            'Reproductive symptoms reported across 12 dairy holdings',
            'Unscreened breeding stock introduced last month',
            'Bulk milk serology tests showing antibody elevation',
            'Para-veterinary reporting delay of 36 hours',
          ],
          recommendedAction: 'Execute serological surveillance and herd segregation advisory.',
          normX: 0.25,
          normY: 0.35,
        ),
        DistrictRiskProfile(
          name: 'Jalgaon',
          state: 'Maharashtra',
          riskScore: 62,
          riskLevel: 'HIGH',
          cases: 39,
          mortality: 3,
          vaccinationCoverage: 67,
          trend: '↑ 8%',
          primaryDisease: 'Haemorrhagic Septicaemia (HS)',
          whyHighRisk: [
            'Acute respiratory distress in draft bullocks',
            'Low pre-monsoon HS booster coverage',
            'Riverine floodplain livestock grazing',
            'Historical vulnerability in Tapi basin',
          ],
          recommendedAction: 'Pre-position emergency antibiotics and activate mobile vet van.',
          normX: 0.42,
          normY: 0.22,
        ),
        DistrictRiskProfile(
          name: 'Chhatrapati Sambhajinagar',
          state: 'Maharashtra',
          riskScore: 57,
          riskLevel: 'HIGH',
          cases: 38,
          mortality: 3,
          vaccinationCoverage: 68,
          trend: '↑ 9%',
          primaryDisease: 'FMD',
          whyHighRisk: [
            'Vesicular lesion reports from weekly animal fair',
            'Immunity drop in 6-month-old calves',
            'Intense interstate transport corridor transit',
            'Delayed farmer reporting beyond 48 hours',
          ],
          recommendedAction: 'Institute animal market sanitation and barrier inspection.',
          normX: 0.44,
          normY: 0.40,
        ),
        DistrictRiskProfile(
          name: 'Nanded',
          state: 'Maharashtra',
          riskScore: 53,
          riskLevel: 'MEDIUM',
          cases: 31,
          mortality: 2,
          vaccinationCoverage: 72,
          trend: '↑ 5%',
          primaryDisease: 'FMD',
          whyHighRisk: [
            'Border transit points from northern Telangana',
            'Isolated fever spikes in peripheral gaushalas',
            'Moderate vaccination uptake in remote hamlets',
            'Mild pasture flooding along Godavari banks',
          ],
          recommendedAction: 'Strengthen border veterinary checkpost surveillance.',
          normX: 0.66,
          normY: 0.54,
        ),
        DistrictRiskProfile(
          name: 'Solapur',
          state: 'Maharashtra',
          riskScore: 49,
          riskLevel: 'MEDIUM',
          cases: 29,
          mortality: 2,
          vaccinationCoverage: 74,
          trend: '↑ 3%',
          primaryDisease: 'PPR',
          whyHighRisk: [
            'Small ruminant coughing reports in migratory flocks',
            'Drought-induced grazing compression',
            'Moderate vaccine coverage in goat rearers',
            'Inter-flock contact at communal watering points',
          ],
          recommendedAction: 'Prioritize targeted PPR goat vaccination in migratory herds.',
          normX: 0.46,
          normY: 0.76,
        ),
        DistrictRiskProfile(
          name: 'Pune',
          state: 'Maharashtra',
          riskScore: 42,
          riskLevel: 'MEDIUM',
          cases: 24,
          mortality: 1,
          vaccinationCoverage: 78,
          trend: '↓ 4%',
          primaryDisease: 'Anthrax',
          whyHighRisk: [
            'Soil-borne spore persistence in legacy endemic pocket',
            'Single sudden mortality event under lab investigation',
            'High overall vaccination coverage (78%) containing spread',
            'Stable surveillance feed from organized dairies',
          ],
          recommendedAction: 'Complete spore containment and verify disposal protocol.',
          normX: 0.28,
          normY: 0.58,
        ),
        DistrictRiskProfile(
          name: 'Latur',
          state: 'Maharashtra',
          riskScore: 38,
          riskLevel: 'MEDIUM',
          cases: 20,
          mortality: 1,
          vaccinationCoverage: 79,
          trend: '↓ 2%',
          primaryDisease: 'FMD',
          whyHighRisk: [
            'Minor localized cluster in 1 taluka',
            'Vaccination campaign reaching 79% completion',
            'Effective quarantine by village sarpanch network',
            'Declining weekly syndromic reports',
          ],
          recommendedAction: 'Maintain routine surveillance until 14-day zero-case window.',
          normX: 0.58,
          normY: 0.64,
        ),
        DistrictRiskProfile(
          name: 'Kolhapur',
          state: 'Maharashtra',
          riskScore: 34,
          riskLevel: 'MEDIUM',
          cases: 16,
          mortality: 1,
          vaccinationCoverage: 82,
          trend: '↓ 6%',
          primaryDisease: 'Black Quarter (BQ)',
          whyHighRisk: [
            'Sporadic fever cases in young stock',
            'High dairy cooperative veterinary access',
            'Vaccination coverage robust at 82%',
            'Prompt antibiotic treatment initiated',
          ],
          recommendedAction: 'Continue weekly cooperative milk route screening.',
          normX: 0.25,
          normY: 0.84,
        ),
        DistrictRiskProfile(
          name: 'Satara',
          state: 'Maharashtra',
          riskScore: 28,
          riskLevel: 'LOW',
          cases: 11,
          mortality: 0,
          vaccinationCoverage: 88,
          trend: '↓ 8%',
          primaryDisease: 'Routine Surveillance',
          whyHighRisk: [
            'High vaccination saturation (88%)',
            'No confirmed outbreak in past 90 days',
            'Consistent para-vet field health loggings',
            'Clean water infrastructure in dairy belts',
          ],
          recommendedAction: 'Maintain baseline syndromic monitoring.',
          normX: 0.26,
          normY: 0.70,
        ),
        DistrictRiskProfile(
          name: 'Thane',
          state: 'Maharashtra',
          riskScore: 25,
          riskLevel: 'LOW',
          cases: 9,
          mortality: 0,
          vaccinationCoverage: 91,
          trend: '↓ 11%',
          primaryDisease: 'Routine Surveillance',
          whyHighRisk: [
            'Vaccination coverage exceeds state target at 91%',
            'Low density peri-urban dairy holdings',
            'Zero mortality events in current quarter',
            'Rapid veterinary diagnostic access',
          ],
          recommendedAction: 'Maintain baseline monitoring and peri-urban entry inspection.',
          normX: 0.16,
          normY: 0.48,
        ),
      ];

  // Top 4 KPIs
  static const Map<String, dynamic> maharashtraKpis = {
    'activeCases': {'value': '248', 'trend': '+12% this week', 'isNegative': true},
    'highRiskAreas': {'value': '07', 'trend': '3 critical', 'isNegative': true},
    'mortality': {'value': '18', 'trend': '-8% this week', 'isNegative': false},
    'vaccination': {'value': '76%', 'trend': '+5% this month', 'isNegative': false},
  };

  // Why Risk is Increasing (4 Factors with Mini Bars)
  static const List<Map<String, dynamic>> whyRiskFactors = [
    {'title': 'Case growth', 'value': '+18%', 'progress': 0.82, 'isWarning': true},
    {'title': 'Mortality', 'value': '+11%', 'progress': 0.62, 'isWarning': true},
    {'title': 'Vaccination', 'value': '61%', 'progress': 0.40, 'isWarning': true},
    {'title': 'Historical / Env risk', 'value': 'High', 'progress': 0.75, 'isWarning': true},
  ];

  // Priority Actions
  static const List<Map<String, dynamic>> priorityActions = [
    {'icon': '🔴', 'label': '3 Critical Areas', 'detail': 'Nagpur, Amravati, Nashik require containment'},
    {'icon': '🟠', 'label': '4 Areas Need Monitoring', 'detail': 'Jalgaon, Sambhajinagar, Nanded, Solapur'},
    {'icon': '💉', 'label': '2 Vaccination Campaigns Needed', 'detail': 'FMD booster in Nagpur & PPR in Solapur'},
    {'icon': '🧪', 'label': '5 Lab Results Pending', 'detail': 'Serology from TANUVAS / Pune regional labs'},
  ];

  // Recent Alerts (Top 3)
  static const List<Map<String, dynamic>> recentAlerts = [
    {
      'severity': 'critical',
      'title': 'Critical disease risk detected',
      'location': 'Nagpur',
      'time': '12 min ago',
      'disease': 'FMD risk increased to 81%',
      'description': 'Cluster of 14 acute vesicular cases confirmed in rural dairy belt.',
    },
    {
      'severity': 'warning',
      'title': 'Vaccination coverage below threshold',
      'location': 'Nashik',
      'time': '1 hr ago',
      'disease': 'Brucellosis buffer 70%',
      'description': 'Target 85% unmet. 4 breeding units flagged for catch-up drive.',
    },
    {
      'severity': 'info',
      'title': 'Lab result requires review',
      'location': 'Pune',
      'time': '2 hrs ago',
      'disease': 'Anthrax spore confirmation',
      'description': 'Sample #LAB-0891 verified negative. Cordon clearance recommended.',
    },
  ];

  // Full Alerts by Tab
  static List<Map<String, dynamic>> getAlertsByCategory(String category) {
    switch (category) {
      case 'Critical':
        return [
          {
            'severity': 'critical',
            'title': 'Critical disease risk detected',
            'location': 'Nagpur',
            'time': '12 min ago',
            'issue': 'FMD risk increased to 81% (64 active cases)',
            'action': 'Prioritize field vet deployment & 5km ring vaccination.',
          },
          {
            'severity': 'critical',
            'title': 'High morbidity spike in crossbred cattle',
            'location': 'Amravati',
            'time': '34 min ago',
            'issue': 'FMD symptoms surging across 3 adjacent talukas (52 cases)',
            'action': 'Enforce interstate border movement checkpost immediately.',
          },
          {
            'severity': 'critical',
            'title': 'Cluster mortality report verified',
            'location': 'Nashik',
            'time': '1 hr ago',
            'issue': '4 heifer mortalities logged with brucellosis indicators',
            'action': 'Deploy rapid investigation team and herd quarantine.',
          },
        ];
      case 'Warning':
        return [
          {
            'severity': 'warning',
            'title': 'Vaccination coverage below threshold',
            'location': 'Nashik',
            'time': '1 hr ago',
            'issue': 'District coverage 70% (target 85%). 4,200 animals pending.',
            'action': 'Schedule catch-up vaccination drive with mobile van.',
          },
          {
            'severity': 'warning',
            'title': 'Unseasonal rainfall & vector risk',
            'location': 'Jalgaon',
            'time': '3 hrs ago',
            'issue': 'Heavy precipitation in Tapi basin elevating HS vulnerability',
            'action': 'Pre-position emergency veterinary antibiotic stock.',
          },
          {
            'severity': 'warning',
            'title': 'Livestock fair transmission alert',
            'location': 'Chhatrapati Sambhajinagar',
            'time': '5 hrs ago',
            'issue': 'Market screening detected 6 vesicular suspect cows',
            'action': 'Broadcast advisory and suspend uninspected animal trade.',
          },
          {
            'severity': 'warning',
            'title': 'Migratory flock respiratory symptoms',
            'location': 'Solapur',
            'time': '7 hrs ago',
            'issue': 'PPR coughing reported in 3 pastoral sheep bands',
            'action': 'Dispatch small ruminant vaccination team to pasture zones.',
          },
        ];
      case 'Information':
      default:
        return [
          {
            'severity': 'info',
            'title': 'Lab result requires review',
            'location': 'Pune',
            'time': '2 hrs ago',
            'issue': 'Sample #LAB-0891 serology ready: Negative for Anthrax',
            'action': 'Authorize quarantine release for inspected farm holding.',
          },
          {
            'severity': 'info',
            'title': 'Target vaccination milestone achieved',
            'location': 'Thane',
            'time': '6 hrs ago',
            'issue': 'District achieved 91% coverage across dairy cooperatives',
            'action': 'Archive campaign record and transition to maintenance.',
          },
          {
            'severity': 'info',
            'title': 'Routine syndromic sync completed',
            'location': 'Satara',
            'time': '8 hrs ago',
            'issue': '100% field records ingested with 0 packet drops',
            'action': 'No immediate government intervention required.',
          },
        ];
    }
  }
}

